### ISSUE TITLE
Moving objects create issues with reflecting waves

### ISSUE THREAD

**Issue by aetherstorm-dev** [pfalstad/ripplegl#3]
Whenever an object moves faster than the incident waves, the waves amplify massively. Is this intentional?

**Comment by pfalstad** [comment]
hi, I'm not sure what you mean, could you show me an example?

**Comment by aetherstorm-dev** [comment]
[glitch.mov.zip](https://github.com/pfalstad/ripplegl/files/3388203/glitch.mov.zip)

**Comment by pfalstad** [comment]
Are these acoustic waves?  Because moving walls with acoustic waves seem really messed up for me, much worse than this example shows.  I don't know why I didn't notice it before.

**Comment by aetherstorm-dev** [comment]
These are. No light rays ever acted this way in simulation. It's probably because repeated reflections cause amplification, but the energy increases too quickly to be realistic. Eventually the energy carried simply increased to infinity, essentially soft-locking the applet.

**Comment by pfalstad** [comment]
I'm probably going to "fix" this by simply disabling moving walls with acoustic waves.

**Comment by aetherstorm-dev** [comment]
Got it.
